apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: banking-prod

resources:
  - ../../base
  - hpa.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: demo-banking-api

images:
  - name: demo-banking-api
    newName: harness.io/demo-banking-api
    newTag: latest
