apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: banking-prod

resources:
  - namespace.yaml
  - ../../base
  - hpa.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: demo-banking-api

# Image tag is managed by Harness artifact expression <+artifact.image> in deployment.yaml
