apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: banking-dev

resources:
  - namespace.yaml
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: demo-banking-api

images:
  - name: demo-banking-api
    newName: pkg.harness.io/ke-e1fx2so2zal2txqpljg/demo-banking/demo-banking-api
    newTag: latest
